### ISSUE TITLE
Newest Kernel no build for US997? Android 14.

### ISSUE THREAD

**Issue by ghost** [LGE-G5-G6-V20/msm8996_lge_kernel#1]
i noticed the last two builds just dont have US997 listed...

**Comment by AShiningRay** [comment]
Are you sure? BETA11 does have US997 as one of its available [builds](https://github.com/LGE-G5-G6-V20/msm8996_lge_kernel/releases/tag/V0.1-BETA11)

If you're looking at BETA10+, that one was V20-only, since the only difference from BETA10 (which was shoved all the way down for some reason) were V20-specific fixes on its Quad-DAC.
